obj-m := tirdad.o

ccflags-y += -Wall
ccflags-y += -Wextra
ccflags-y += -Werror
ccflags-y += -Wformat
ccflags-y += -Wformat-security
ccflags-y += -Wformat-nonliteral
ccflags-y += -Wno-unused-parameter
